### ISSUE TITLE
It doest work on servers (1.16)

### ISSUE THREAD

**Issue by MBMRMASTAR** [sguest/jei-multiblocks#1]
It works perfectly fine on singleplayer but when I try to use it in a server it doesn't work

[jeimultiblocks-1.16.5-0.0.1.jar](https://www.curseforge.com/minecraft/mc-mods/just-enough-immersive-multiblocks/files/3836732)
Server Software: [Modrith (1.16)](https://mohistmc.com/)

**Comment by sguest** [comment]
Please provide a few more details

- Is there any kind of error thrown, or the recipes simply aren't appearing in JEI?
- Is the mod installed on the server, or are you trying to use it client-only?
- If possible please include a log file from MC when you are trying to use the mod but it's not working

**Comment by MBMRMASTAR** [comment]
The recipes simply aren't appearing in JEI when I'm on a serverz
The mod is installed in both client and server
Unfortunately I can't provide a log file sorry

[ModPack](https://www.curseforge.com/minecraft/modpacks/into-the-infinity)
Server IP:172.96.172.162:25568

https://github.com/sguest/jei-multiblocks/assets/127889810/dd2c9609-8241-4c59-a198-f44cb598cf5f


https://github.com/sguest/jei-multiblocks/assets/127889810/a9d682b7-f1f0-47c2-b718-b8b1184c8edf

**Comment by sguest** [comment]
Thank you for providing the log and additional info. I can see where the crash is happening from the log, and am able to reproduce with my own testing. Unfortunately, I'm not sure there is a good fix for this issue on the 1.16 version.

The logs point to the crash happening deep within Immersive Engineering's code base, after this mod has called into it in order to get the list of blocks involved in a given multiblock. The 1.18 and newer versions of this mod use a slightly more stable API call into IE to do this that isn't available in the 1.16 version. Honestly I don't have a sufficiently deep understanding of how IE manages its internal data structures to know why this is happening for 1.16 in server play only. It could also be related to JEI lifecycle events firing in a different order in older MC versions. Even if I could track down exactly what is the problem, there's a chance it would require a change to one of those mods, and either one is unlikely to want to engage in changing things for 1.16 at this point, very understandably so as these are quite old mod versions.

Therefore I'm sadly going to have to close this as won't fix.
